GT.CRMApplication.WebMVC/Controllers/LeadAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DM.Utilities.NetFramework.Databases.MsSQLs;
using DM.Utilities.NetFramework.Models;
using DM.Utilities.NetFramework.Generics;
using GT.InboundApplication.Model.CRM;
using GT.InboundApplication.Model.Common;
using GT.InboundApplication.Model.GTApplicationDB;
using GT.CRMApplication.WebMVC5.Helpers;
using System.Data.Entity.Validation;
using System.Threading;
using System.Globalization;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Web.Script.Serialization;
using System.Configuration;
using System.Threading.Tasks;
using System.Net;

using ExcelDataReader;
using System.Data;
using System.Text.RegularExpressions;
using GT.CRMApplication.WebMVC5.ViewModels;
using ClosedXML.Excel;
using Newtonsoft.Json.Linq;
using SimpleJson;
using Newtonsoft.Json;
using System.Text;

namespace GT.CRMApplication.WebMVC5.Controllers
{
    //[Authorize]
    public class LeadAssignmentController : Controller
    {        
        private ApplicationDbContext appdb = new ApplicationDbContext();
        IGTCRMContext db = new IGTCRMContext();
        IGTCRMContext crm = new IGTCRMContext();
        ActiveUserModel _ActiveUserModel = new ActiveUserModel();

        public class SearchLeadClass
        {
            public string phonenumber { get; set; }
            public string name { get; set; }
            public string createdate { get; set; }
            public string response { get; set; }
            public string[] responses { get; set; }
            public string reason { get; set; }
            public string leadflag { get; set; }
            public string sup { get; set; }
            public string tsr { get; set; }
            public string[] tsrs { get; set; }
            public string receiver { get; set; }
            public string callcount { get; set; }
            public int? leadage1 { get; set; }
            public int? leadage2 { get; set; }
            public string daterange { get; set; }
            public string product { get; set; }
            public string tag { get; set; }
            public string leaddb { get; set; }
            public int? expirein { get; set; }
            public string calldate { get; set; }
            public string expiredate { get; set; }
            public string issuedate { get; set; }
            public string policyno { get; set; }
        }

        public class MyLeadDisplayClass
        {
            public string TM { get; set; }
            public string Name { get; set; }
            public string Telphone { get; set; }
            public string PolicyNo { get; set; }
            public string CreatedDate { get; set; }
            public string IssueDate { get; set; }
            public string ExpireDate { get; set; }
            public string CallSource { get; set; }
            public string Product { get; set; }
            public string ResponseCategoryCode { get; set; }
            public string ResponseReason { get; set; }
            public dynamic Remark { get; set; }
            public string CallDate { get; set; }
            public int? CallCount { get; set; }
            public int TodayCall { get; set; }
            public string Appointment { get; set; }
            public string AppointmentTime { get; set; }
            public string AppointmentTopic { get; set; }
            public long LeadProfileId { get; set; }
            public int Countdown { get; set; }
            public string Priority { get; set; }
            public bool IsDMC { get; set; }
            public string XSellLabel { get; set; }
            public string LeadFlag { get; set; }
            public decimal? TopConversion { get; set; }
            public string TopTsr { get; set; }
            public decimal? MyConversion { get; set; }
            public string RemainingHotTime { get; set; }
            public bool IsDownloaded { get; set; }
        }

        public class DistributeLeadViewModel
        {
            public ActiveUserModel.ActiveUserClass tsr { get; set; }
            public int leadqty { get; set; }
            public int currentlead { get; set; }
            public int OpenLead { get; set; }
            public bool isSelected { get; set; }
        }

        public LeadAssignmentController()
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-GB");
            db.Database.Log = sql => System.Diagnostics.Debug.Write(sql);
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            appdb.Dispose();
            db.Dispose();
            crm.Dispose();
        }

        #region Action

        // GET: LeadProfile
        public ActionResult Index(string tag)
        {
            if (!User.IsAdmin())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            SearchLeadClass criteria = new SearchLeadClass() { createdate = DateTime.Today.ToShortDateString() };
            
            LoadTsr();
            LoadResponseExtend();
            LoadReason();
            ViewBag.SearchData = criteria;
            return View();
        }

        [HttpPost]
        public ActionResult Search(SearchLeadClass criteria)
        {
            var createdate = criteria.createdate.ParseToDate();
            var leadset = db.LeadProfileSet.ActiveSet();
            if (!String.IsNullOrEmpty(criteria.createdate)) leadset = leadset.CreateDateInRange(criteria.createdate);// leadset.Where(x => DbFunctions.TruncateTime(x.CreatedDate) == createdate);
            if (!String.IsNullOrEmpty(criteria.name)) leadset = leadset.Where(x => (x.FirstName + " " + x.LastName).Contains(criteria.name));
            if (!String.IsNullOrEmpty(criteria.phonenumber))
            {
                var telephone = criteria.phonenumber.Replace(" ", "");
                List<long> prospectids = new List<long>();
                leadset = leadset.Where(x => x.TelPhone.Replace(" ", "").Contains(telephone));
            }
            if (criteria.responses != null) leadset = leadset.Where(c => criteria.responses.Contains(c.RecentLeadAssignment.ResponseCategoryCode));
            if (!String.IsNullOrEmpty(criteria.leadflag)) leadset = leadset.Where(c => c.LeadFlag == criteria.leadflag);
            if (!String.IsNullOrEmpty(criteria.tsr)) leadset = leadset.LastAssignTo(criteria.tsr);
            if (!String.IsNullOrEmpty(criteria.receiver)) leadset = leadset.Where(c => c.RecentLeadAssignment.ReceiverUserId == criteria.receiver);
            ViewBag.SearchData = criteria;
            LoadTsr();
            LoadLeadFlag("N");
            LoadResponseExtend(criteria.response);
            return View("Index",leadset.ToList());
        }

        public ActionResult RetrieveLeads(SearchLeadClass criteria)
        {
            var createdate = criteria.createdate.ParseToDate();
            var leadset = db.LeadProfileSet.ActiveSet();
            if (!string.IsNullOrEmpty(criteria.product)) leadset = leadset.Where(c => c.ProductGroup == criteria.product);
            if (!String.IsNullOrEmpty(criteria.createdate)) leadset = leadset.CreateDateInRange(criteria.createdate);
            if (!String.IsNullOrEmpty(criteria.issuedate)) leadset = leadset.IssueDateInRange(criteria.issuedate);
            if (!String.IsNullOrEmpty(criteria.expiredate)) leadset = leadset.ExpireDateInRange(criteria.expiredate);
            if (!String.IsNullOrEmpty(criteria.name)) leadset = leadset.Where(x => x.FirstName.Contains(criteria.name));
            if (!String.IsNullOrEmpty(criteria.phonenumber))
            {
                var telephone = criteria.phonenumber.Replace(" ", "");
                leadset = leadset.Where(x => x.TelPhone.Contains(telephone));
            }
            
            //if (criteria.responses != null) leadset = leadset.Where(c => criteria.responses.Contains(c.RecentLeadAssignment.ResponseCategoryCode));
            if (!String.IsNullOrEmpty(criteria.response))
            {
                var responses = criteria.response.Replace("[", "").Replace("]", "").Split(',');
                leadset = leadset.Where(c => responses.Contains(c.RecentLeadAssignment.ResponseCategoryCode));
            }
            if (!String.IsNullOrEmpty(criteria.reason))
            {
                var reasons = criteria.reason.Replace("[", "").Replace("]", "").Split(',');
                leadset = leadset.Where(c => reasons.Contains(c.RecentLeadAssignment.ResponseReasonCode));
            }
            if (!String.IsNullOrEmpty(criteria.tsr))
            {
                var tsrs = criteria.tsr.Split(',');
                leadset = leadset.LastAssignTo(tsrs);
            }
            if (!String.IsNullOrEmpty(criteria.receiver))
            {
                var tsrs = criteria.receiver.Split(',');
                leadset = leadset.Where(c => tsrs.Contains(c.RecentLeadAssignment.ReceiverUserId));
            }
            //if (!String.IsNullOrEmpty(criteria.receiver)) leadset = leadset.Where(c => c.RecentLeadAssignment.ReceiverUserId == criteria.receiver);

            if (criteria.tag == "newlead")
            {
                leadset = db.LeadProfileSet.WaitingForAssign(30);
            }
            else if (criteria.tag == "expire")
            {
                var today = DateTime.Today;
                leadset = db.LeadProfileSet.ActiveSet().Where(c=>c.ExpireDate == today && (c.RecentLeadAssignment.ResponseCategoryCode==""||c.RecentLeadAssignment.ResponseCategoryCode=="1"));
            }
            var showsimplesource = User.IsSimpleSource();
            var usecol = from row in leadset
                         select new
                         {
                             row.LeadProfileId,
                             row.TM,
                             row.FirstName,

GT.CRMApplication.WebMVC/Views/LeadAssignment/AssignLead.cshtml
@using DM.Utilities.NetFramework.Databases.MsSQLs;
@using DM.Utilities.NetFramework.DataTables;
@using DM.Utilities.NetFramework.Models;
@using DM.Utilities.NetFramework.Generics;
@using GT.InboundApplication.Model.Common;
@model GT.InboundApplication.Model.CRM.LeadProfile
@{
    ViewBag.Title = "จัดการลีด";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-sm-12">
        <div class="col-sm-12">
            <h2><i class="fa fa-cube"></i>ลีด</h2>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("รายการลีด", "Index", "LeadAssignment")
                </li>
                <li class="active">
                    <strong>จัดการลีด</strong>
                </li>
            </ol>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-8">
                <div class="ibox border-red">
                    <div class="ibox-title">
                        <h5>
                            <i class="fa fa-plus"></i> จัดการลีด
                        </h5>
                    </div>
                    <div class="ibox-content animated fadeInDown">
                        <h4>
                            @(Model.FirstName == "" ? "ไม่มีชื่อ" : string.Format("{0} {1} {2}", Model.Salutation, Model.FirstName, Model.LastName))                            
                        </h4>
                        <table class="footable table table-stripped table-hover">
                            <tr>
                                <td>เบอร์มือถือ : <b>@(Model.TelPhone.IsNullOrEmpty() ? "-" : Model.TelPhone)</b></td>
                            </tr>
                            <tr>
                                <td>เบอร์โทรศัพท์บ้าน : <b>@(Model.TelPhone2.IsNullOrEmpty() ? "-" : Model.TelPhone2)</b></td>
                            </tr>
                            <tr>
                                <td>อีเมล์ : <b>@(Model.Email.IsNullOrEmpty() ? "-" : Model.Email)</b></td>
                            </tr>
                            <tr>
                                <td>เพิ่มโดย : <b>@(String.IsNullOrEmpty(ViewBag.CreateByName) ? "-" : ViewBag.CreateByName)</b></td>
                            </tr>
                            <tr>
                                <td>
                                    @{List<GT.InboundApplication.Model.CRM.LeadAssignment> leadAssignments = Model.LeadAssignmentSet.ToList(); }
                                    ประวัติการมอบหมาย @leadAssignments.Count ครั้ง
                                    @if (leadAssignments.Count > 0)
                                    {
                                        <div class="ibox-tools">
                                            <a data-toggle="collapse" data-target="#div-assign-his">
                                                <i class="fa fa-chevron-down"></i>แสดงประวัติการมอบหมาย
                                            </a>
                                        </div>
                                        <div id="div-assign-his" class="collapse">
                                            <table class="table table-striped table-condensed">
                                                <thead>
                                                    <tr>
                                                        <th>วันที่มอบหมาย</th>
                                                        <th>ผู้รับมอบ</th>
                                                        <th>การสนทนาล่าสุด</th>
                                                        <th>ผลการสนทนา</th>
                                                        <th data-orderable="false">เหตุผล</th>
                                                        <th data-orderable="false">หมายเหตุ</th>
                                                        <th>Last Contact</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var item in leadAssignments.OrderBy(c => c.AssignDate))
                                                    {
                                                        <tr data-assignid="@item.LeadAssignmentId">
                                                            <td>@item.AssignDate</td>
                                                            <td>@item.ReceiverUserName</td>
                                                            <td>@item.Activity</td>
                                                            <td>@Html.DisplayFor(@m => @item.ResponseCategoryCode, "SalesResponse")</td>
                                                            <td>@item.ResponseReason</td>
                                                            <td>@item.Detail</td>
                                                            <td>
                                                                <i class='fa fa-clock-o'></i>
                                                                @item.CallDate
                                                            </td>
                                                            @if (User.IsSuperAdmin())
                                                            {
                                                                <td>@item.UnAssignDate</td>
                                                                <td>@item.LeadFlag</td>
                                                                <td>
                                                                    <div class="btn-group">
                                                                        <a href="@Url.Action("DeleteAssignment", new { id = item.LeadAssignmentId })" title="Delete Assignment" class="btn btn-danger btn-xs"><i class="fa fa-fw fa-trash"></i></a>
                                                                        <a href="@Url.Action("ToggleAssignmentFlag", new { id = item.LeadAssignmentId })" title="Toggle Assignment Flag" class="btn btn-success btn-xs"><i class="fa fa-fw fa-toggle-on"></i></a>
                                                                        <a href="@Url.Action("MakeActiveAssignment", new { id = item.LeadAssignmentId })" title="Make Active Assignment" class="btn btn-info btn-xs"><i class="fa fa-fw fa-level-up"></i></a>
                                                                    </div>
                                                                </td>
                                                            }
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    }
                                </td>
                            </tr>
                        </table>
                        <div class="form-horizontal">                            
                            <div class="form-group">
                                <label class="control-label col-sm-3">ผู้รับมอบหมาย:</label>
                                <div class="col-sm-4">
                                    @Html.HiddenFor(model => model.RecentLeadAssignment.ReceiverUserName, new { @id = "txt-receiver-name" })
                                    @Html.DropDownListFor(modelItem => modelItem.RecentLeadAssignment.ReceiverUserId, (IEnumerable<SelectListItem>)ViewBag.ActiveUser, "เลือก", new { @id = "ddl-receiver", @class = "form-control", @style = "width:100%" })
                                    @*@Html.DropDownListFor(modelItem => modelItem.RecentLeadAssignment.ReceiverUserId, (IEnumerable<SelectListItem>)ViewBag.ActiveUser, "เลือก", new { @id = "ddl-receiver", @class = "form-control" })*@
                                </div>
                            </div>
                            @if (Model.Status == true && Model.LeadFlag != "D")
                            {
                                using (var db = new GT.InboundApplication.Model.CRM.IGTCRMContext())
                                {
                                    if (User.IsInRole("SUPERVISOR") && (Model.LeadAge > GT.CRMApplication.WebMVC5.Helpers.AppConfig.SupExpireDays || ViewBag.IsAdminLead == true))
                                    {
                                        <div class="form-group">
                                            <div class="col-sm-8 col-sm-offset-3">
                                                <p class="text-warning">    ลีดอายุเกิน 60 วัน หรือลีดไม่สามารถแก้ไขโดย Supervisor</p>
                                            </div>
                                        </div>
                                    }
                                    else if (db.Prospect_ProfileSet.Any(c => c.ProspectId == Model.ProspectId && c.OptOut == "Y"))
                                    {
                                        <div class="form-group">
                                            <div class="col-sm-8 col-sm-offset-3">
                                                <p class="text-warning">    ไม่ต้องการให้ติดต่ออีก</p>
                                            </div>
                                        </div>
                                    }
                                    else if (User.IsManager() || (User.IsAdmin() && (Model.LeadAge <= GT.CRMApplication.WebMVC5.Helpers.AppConfig.SupExpireDays && ViewBag.IsAdminLead == false)))
                                    {
                                        <div class="form-group">
                                            <div class="form-group">
                                                @Html.HiddenFor(modelItem => modelItem.LeadProfileId)
                                                <div class="col-sm-4 col-sm-offset-3">
                                                    @if (Model.LeadFlag == "N" && Model.LeadAssignmentSet.Any())
                                                    {
                                                        <div class="checkbox hidden">
                                                            <input type="checkbox" id="keepnew" name="keepnew" value="true">
                                                            <label for="keepnew">รักษาสถานะเป็นลีดใหม่</label>
                                                        </div>
                                                    }
                                                    <button type="submit" value="CreateProfile" id="btn_submit" class="btn btn-primary">บันทึก</button>
                                                    <a href="@Url.Action("Index","LeadAssignment")" class="btn btn-default">Cancel</a>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                @Html.Action("ViewMainProfile", "Prospect", new { @id = @Model.ProspectId, @telephone = @Model.TelPhone, @telephone2 = @Model.TelPhone2, @tel2ex = @Model.TelPhone2_Extension })
            </div>
        </div>
    </div>
}
@section Styles {
    @Styles.Render("~/plugins/select2/css")
}
@section Scripts {
    @Scripts.Render("~/plugins/select2")
}
<script type="text/javascript">
    $().ready(function () {
        $("#btn_submit").click(function () { validateform(); return false; });
        $("#ddl-callsource").change(function () {
            if ($("#ddl-callsource").val() != "") {
                $("#txt-callsource-name").val($("#ddl-callsource>option:selected").html());
            } else {
                $("#txt-callsource-name").val("");
            }
        });
        $("#ddl-receiver").select2();
        $("#ddl-receiver").change(function () {
            if ($("#ddl-receiver").val() != "") {
                $("#txt-receiver-name").val($("#ddl-receiver>option:selected").html());
            } else {
                $("#txt-receiver-name").val("");
            }
        });
        $("#ddl-product").change(function () {
            if ($("#ddl-product").val() != "") {
                $("#txt-product-name").val($("#ddl-product>option:selected").html());
            } else {
                $("#txt-product-name").val("");
            }
        });
    });
    function validateform() {
        try {
            // validate input format.
            var message = "";
            var createby = "";
            if ($("#ddl-callsource").length > 0 && $("#ddl-callsource").val().length <= 0) {
                message += "<li> - ลีดต้นทาง  </li>";
            }

            if (message != "") {
                pop_message('กรุณาระบุข้อมูลต่อไปนี้', '<ul>' + message + '</ul>', 'warning');
                return false;
            }
            $("#btn_submit").attr("disabled", true);
            $('#main-div form').submit();

            //return false;
        }
        catch (e) { console.log(e.stack); return false; }
    }
</script>

GT.CRMApplication.WebMVC/Views/LeadAssignment/EditLeadProfile.cshtml
@{
    ViewBag.Title = "EditLeadProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditLeadProfile</h2>

GT.CRMApplication.WebMVC/Views/LeadAssignment/ImportLead.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ImportLead</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

GT.CRMApplication.WebMVC/Views/LeadAssignment/NewLeadAmount.cshtml
@using GT.InboundApplication.Model.Common
@using System.Configuration
@model GT.CRMApplication.WebMVC5.ViewModels.NewLeadAmountViewModel
@{
    var linkcrm = Request.CRMLink();
    if (User.IsAdmin())
    {
    <div class="pull-left">
        จำนวนลีดเข้าใหม่รอมอบหมาย <a href="@linkcrm/LeadAssignment?tag=newlead" class="badge @(Model.NewLead == 0?"badge-success":"badge-primary")">@Model.NewLead</a>
        @if (Model.NewLead > 0)
        {
            <a href="@linkcrm/LeadAssignment?tag=newlead" class="btn btn-xs btn-primary">แสดง</a>
        }
        <br />
        จำนวนลีดหมดอายุวันนี้ <a href="@linkcrm/LeadAssignment?tag=expire" class="badge @(Model.ExpireLead == 0 ? "badge-success" : "badge-primary")">@Model.ExpireLead</a>
        @if (Model.ExpireLead > 0)
        {
            <a href="@linkcrm/LeadAssignment?tag=expire" class="btn btn-xs btn-primary">แสดง</a>
        }
    </div>
    }
    else
    {
    <div class="pull-left">
        จำนวนลีดเข้าใหม่ที่ยังไม่ได้ติดต่อ <a href="@linkcrm/LeadAssignment/MyLead?tag=newlead" class="badge @(Model.NewLead == 0?"badge-success":"badge-primary")">@Model.NewLead</a>
        @if (Model.NewLead > 0)
        {
            <a href="@linkcrm/LeadAssignment/MyLead?tag=newlead" class="btn btn-xs btn-primary">แสดง</a>
        }
        <br />
        จำนวนลีดหมดอายุวันนี้ที่ยัง Follow up <a href="@linkcrm/LeadAssignment/MyLead?tag=expire" class="badge @(Model.ExpireLead == 0 ? "badge-success" : "badge-primary")">@Model.ExpireLead</a>
        @if (Model.ExpireLead > 0)
        {
            <a href="@linkcrm/LeadAssignment/MyLead?tag=expire" class="btn btn-xs btn-primary">แสดง</a>
        }
    </div>
    }
}

GT.CRMApplication.WebMVC/Views/LeadAssignment/UploadLead.cshtml
@model IEnumerable<GT.InboundApplication.Model.CRM.LeadProfile>
@{
    ViewBag.Title = "Upload Lead Profiles";
}
<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-sm-12">
        <div class="col-sm-12">
            <h2><i class="fa fa-cube"></i>ลีด</h2>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("รายการลีดโปรไฟล์", "Index", "LeadAssignment")
                </li>
                <li class="active">
                    <strong>นำเข้าข้อมูลลีด</strong>
                </li>
            </ol>
        </div>
    </div>
</div>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInUp">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>นำเข้าข้อมูลลีด</h5>
                    </div>
                    <div class="ibox-content">
                        <span class="btn btn-success fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>เลือกไฟล์...</span>
                            <!-- The file input field used as target for the file upload widget -->
                            <input id="fileupload" type="file" name="leadsfile" data-url="ParseLeadsFile">
                        </span>
                        <button type="submit" id="btn_submit" class="btn btn-primary">นำเข้า</button>
                        <div id="progress" class="progress">
                            <div class="progress-bar progress-bar-success"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div id="div-display-lead">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
    @Styles.Render("~/plugins/blueimp/css")
    <style type="text/css">
        .iffyTip {
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            width: 100px;
        }
    </style>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/plugins/jeditable")
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/blueimp")
    <script type="text/javascript">
        $(document).ready(function () {
            //$('.dataTables').DataTable();
            $('#fileupload').fileupload({
                replaceFileInput:false,
                dataType: 'html',
                done: function (e, data) {
                    $("#div-display-lead").html(data.result);
                },
                progressall: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $('#progress .bar').css(
                        'width',
                        progress + '%'
                    );
                },
                error: function () {
                    swal("เกิดข้อผิดพลาดในการทำงาน", "", "error");
                    $("#fileupload").val("");
                }
            });
            $("#btn_submit").click(function () {
                if ($("#tbody-leads>tr").length == 0) {
                    swal("กรณากดเลือกไฟล์ก่อนนำเข้า", "", "warning");
                    return false;
                }
                $(this).attr("disabled", true);
                $('#main-div form').submit();
            });
        });
    </script>
}
<script type="text/javascript">
    $().ready(function () {
        $("#ddl-callsource").change(function () {
            if ($("#ddl-callsource").val() != "") {
                $("#txt-callsource-name").val($("#ddl-callsource>option:selected").html());
            } else {
                $("#txt-callsource-name").val("");
            }
        });
        $("#ddl-product").change(function () {
            if ($("#ddl-product").val() != "") {
                $("#txt-product-name").val($("#ddl-product>option:selected").html());
            } else {
                $("#txt-product-name").val("");
            }
        });
    });
</script>