GT.CRMApplication.WebMVC/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using DM.Utilities.NetFramework.Databases.MsSQLs;
using DM.Utilities.NetFramework.DataTables;
using DM.Utilities.NetFramework.Models;
using DM.Utilities.NetFramework.Generics;
using GT.InboundApplication.Model.CRM;

namespace GT.CRMApplication.WebMVC5.Controllers
{
    public class ActivityController : Controller
    {
        private IGTCRMContext db = new IGTCRMContext();

        // GET: /Activity/
        public ActionResult Index()
        {
            return View(db.ActivitySet.ToList());
        }

        // GET: /Activity/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.ActivitySet.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: /Activity/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Activity/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include="ActivityId,Code,Name,Note,Active,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate,IsSupportInboundCall,IsSupportOutboundCall,IsSupportFollowupCall,IsSupportUnknownPerson,IsSupportProspectPerson")] Activity activity)
        {
            if (ModelState.IsValid)
            {
				activity.CreatedBy =
				activity.UpdatedBy = User.Identity.GetUserId();
				activity.CreatedDate =
                activity.UpdatedDate = DateTime.Now;
                db.ActivitySet.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        // GET: /Activity/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.ActivitySet.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: /Activity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include="ActivityId,Code,Name,Note,Active,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate,IsSupportInboundCall,IsSupportOutboundCall,IsSupportFollowupCall,IsSupportUnknownPerson,IsSupportProspectPerson")] Activity activity)
        {
            if (ModelState.IsValid)
            {
				activity.UpdatedBy = User.Identity.GetUserId();
			    activity.UpdatedDate = DateTime.Now;
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        // GET: /Activity/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.ActivitySet.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: /Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Activity activity = db.ActivitySet.Find(id);
            db.ActivitySet.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GT.CRMApplication.WebMVC/Controllers/ProspectController.cs
using GT.CRMApplication.WebMVC5.Helpers;
using DM.Utilities.NetFramework.Databases.MsSQLs;
using DM.Utilities.NetFramework.DataTables;
using DM.Utilities.NetFramework.Models;
using DM.Utilities.NetFramework.Generics;
using GT.InboundApplication.Model.Common;
using GT.InboundApplication.Model.CRM;
using GT.InboundApplication.Model.GTApplicationDB;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace GT.CRMApplication.WebMVC5.Controllers
{

    [Authorize]
    public class ProspectController : Controller
    {
        private IGTCRMContext db = new IGTCRMContext();

        private enum Source
        {
            None = 0,
            LeadAssignment = 1,
            ECommerce = 2
        }

        public ProspectController()
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-GB");
            db.Database.Log = sql => System.Diagnostics.Debug.Write(sql);
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            db.Dispose();
        }

        public long LeadAssignmentId
        {
            get
            {
                var laid = Session["LeadAssignmentId"];
                if (laid != null)
                {
                    return Convert.ToInt64(laid);
                }
                return 0;
            }
            set
            {
                Session["LeadAssignmentId"] = value;
            }
        }

        private Source ActivitySource
        {
            get
            {
                var s = Session["Prospect/ActivitySource"];
                if (s != null) return (Source)s;
                return Source.None;
            }
            set
            {
                Session["Prospect/ActivitySource"] = value;
            }
        }

        private long? ProspectId
        {
            get
            {
                var s = Session["Prospect/ProspectId"];
                if (s != null) return (long)s;
                return null;
            }
            set
            {
                Session["Prospect/ProspectId"] = value;
            }
        }

        private string CallFrom
        {
            get
            {
                var s = Session["Prospect/CallFrom"];
                if (s != null) return (string)s;
                return null;
            }
            set
            {
                Session["Prospect/CallFrom"] = value;
            }
        }

        #region GET

        public ActionResult Index()
        {
            ViewBag.ResponseCategory = new SelectList(db.ResponseCategorySet.ToList(), "ResponseCategoryId", "Name");
            ViewBag.TotalProspect = db.Prospect_ProfileSet.Count();

            //var callsource = this._GetCallSource();
            //ViewBag.CallSource = new SelectList(callsource, "name", "name");
            _LoadCallSource();
            //_LoadResponse();

            return View();
        }

        public ActionResult Search()
        {
            ViewBag.ResponseCategory = new SelectList(db.ResponseCategorySet.ToList(), "ResponseCategoryId", "Name");
            ViewBag.TotalProspect = db.Prospect_ProfileSet.Count();

            _LoadCallSource();
            _LoadResponse();
            ViewBag.OfferProduct = new SelectList(db.OfferProductSet.Where(x => x.Active.Value).ToList(), "OfferProductId", "Name");

            return View();
        }

        public ActionResult CreateProfile()
        {
            Prospect_Profile newprofile = new Prospect_Profile();
            this._PopulateProfile();
            return View(newprofile);
        }

        public ActionResult EditProfile(int? id)
        {
            if (id.IsNullOrEmpty())
            {
                return HttpNotFound("Id is Null.");
            }
            Prospect_Profile profile = db.Prospect_ProfileSet.SingleOrDefault(item => item.ProspectId == id.Value);
            if (profile.IsNullOrEmpty())
            {
                return HttpNotFound("Profile Not Found!");
            }
            this._PopulateProfile(profile);
            return View(profile);
        }

        public ActionResult Detail(long id)
        {
            var profile = db.Prospect_ProfileSet.SingleOrDefault(c => c.ProspectId == id);
            if (profile.IsNullOrEmpty())
            {
                return HttpNotFound("Profile Not Found!");
            }
            var lead = db.LeadProfileSet.ActiveSet().FirstOrDefault(c => c.ProspectId == profile.ProspectId);
            if (lead != null)
            {
                ViewBag.LeadProfile = db.LeadProfileSet.ActiveSet().FirstOrDefault(c => c.ProspectId == profile.ProspectId);                
                if (profile.Prospect_Activity.Any())
                {
                    using (var appdb = new ApplicationDbContext())
                    {
                        ViewBag.User = appdb.Users.Find(profile.Prospect_Activity.OrderByDescending(o => o.CreatedDate).First().CreatedBy);
                    }
                }
            }
            ConsentHelper.GetConsent(ViewBag, profile);
            return View("IncomingCall", "_EmptyLayout", profile);
            //return PartialView("IncomingCall", profile);
        }
        
        private Prospect_Activity prepareCreateActivity(long? id,string callfrom,out ActionResult result)
        {
            if (id.IsNullOrEmpty())
            {
                result = HttpNotFound("Id is Null.");
                return null;
            }
            Prospect_Profile profile = db.Prospect_ProfileSet.SingleOrDefault(item => item.ProspectId == id.Value);
            if (profile.IsNullOrEmpty())
            {
                result = HttpNotFound("Profile Not Found!");
                return null;
            }
            callfrom = getCallFrom(id, callfrom);
            Prospect_Activity newactivity = new Prospect_Activity()
            {
                Prospect_Profile = profile,
                CallTime = DateTime.Now.ToString("HH:mm"),
                CallFrom = callfrom
            };

            ViewBag.RunScript = "AfterScript();";
            this._PopulateProfileActivity();
            //if (!User.IsSuperAdmin())
            {
                var noassignment = _CheckAssignment(newactivity);
                if (noassignment != null)
                {
                    result = noassignment;
                    return null;
                }
            }
            var leadProfile = db.LeadAssignmentSet.Find(newactivity.LeadAssignmentId).LeadProfile;
            ViewBag.LeadProfile = leadProfile;
                        
            using (var appdb = new ApplicationDbContext())
            {
                ViewBag.User = appdb.Users.Find(User.Identity.GetUserId());
            }
            ConsentHelper.GetConsent(ViewBag, newactivity.Prospect_Profile);
            result = null;
            return newactivity;
        }
        

        public ActionResult CreateActivity(long? id,string callfrom=""){
            ActionResult result;
            Prospect_Activity newactivity = prepareCreateActivity(id, "Application", out result);
            if (result != null) return result;
            return View(newactivity);
        }

       

        public ActionResult DeleteActivity(int? id, int? activitycode)
        {
            var act = db.Prospect_ActivitySet.Find(activitycode);
            return View(act);
        }

        [HttpDelete]
        public ActionResult DeleteActivity(Prospect_Activity entity)
        {
            var act = db.Prospect_ActivitySet.Find(entity.ItemId);
            if (act == null)
            {
                return RedirectToAction("MainProfile", new { id = entity.Prospect_ProfileProspectId, message = "Activity is not found." });
            }
            var profileid = act.Prospect_ProfileProspectId;
            if (!act.AppointmentId.IsNullOrEmpty())
            {
                var appointment = db.Prospect_AppointmentSet.Find(act.AppointmentId);
                if (appointment != null)
                {
                    if (db.Prospect_ActivitySet.Any(c => c.ItemId > appointment.Prospect_Activity.ItemId))
                    {
                        appointment.IsReply = false;
                    }
                }
            }
            //var profile = act.Prospect_Profile;
            //profile.Prospect_Activity.Remove(act);
            if (act.Prospect_Appointment != null) db.Entry(act.Prospect_Appointment).State = EntityState.Deleted;
            db.Entry(act).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("MainProfile", new { @id = profileid, message = "Delete Success" });
        }

        public ActionResult CreateFollowUpActivity(long? id, int appointmentcode)
        {
            string connectionString = db.Database.Connection.ConnectionString;
            var prospectid = id;
            if (prospectid.IsNullOrEmpty())
            {
                return HttpNotFound("Id is Null.");
            }
            Session.Remove("Appointment");
            Prospect_Profile profile = db.Prospect_ProfileSet.SingleOrDefault(item => item.ProspectId == prospectid.Value);
            if (profile.IsNullOrEmpty())
            {
                return HttpNotFound("Specific Profile is Not Found!");
            }

            getCallFrom(id, CRMExtension.CallFrom.Appointment);
            Prospect_Activity newactivity = new Prospect_Activity()
            {
                Prospect_Profile = profile,

GT.CRMApplication.WebMVC/Views/Prospect/CreateActivity.cshtml
@using DM.Utilities.NetFramework.Databases.MsSQLs;
@using DM.Utilities.NetFramework.DataTables;
@using DM.Utilities.NetFramework.Models;
@using DM.Utilities.NetFramework.Generics;
@using GT.InboundApplication.Model.Common;
@model GT.InboundApplication.Model.CRM.Prospect_Activity
@{
    ViewBag.Title = "New Activity";
}
<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-md-12">
        <div class="col-md-10">
            <h2>ผู้ติดต่อ</h2>
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @if (User.IsAdmin())
                    {
                        @Html.ActionLink("รายการลีด", "Index", "LeadAssignment")
                    }
                    else
                    {
                        @Html.ActionLink("My Lead", "MyLead", "LeadAssignment")
                    }
                </li>
                <li>
                    <a href="@Url.Action("MainProfile", "Prospect", new { @id = Model.Prospect_Profile.ProspectId })">ประวัติผู้ติดต่อ</a>
                </li>
                <li class="active">
                    <strong>เพิ่มข้อมูลการติดต่อ</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-4">
            @Html.Partial("_MainProfile", Model.Prospect_Profile)
        </div>
        <div class="col-sm-8">
            <div class="ibox">
                <div class="ibox-title red-bg">
                    <h5>                        
                        <i class="fa fa-phone"></i>&nbsp;&nbsp;&nbsp;สร้างการติดต่อใหม่ &nbsp;&nbsp;
                    </h5>
                </div>
                @if (ViewBag.NoAssignment == null)
                {
                    using (Html.BeginForm("CreateActivity", "Prospect"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Partial("_ActivityForm", Model)
                    }
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/onviews/Prospect/ActivityForm")
    @Scripts.Render("~/bundles/vuejs")
    @Scripts.Render("~/plugins/fullCalendar")   

    <script type="text/javascript">
        $(document).ready(function () {
            bindevent_control();
            $('#appointment-div').hide();
        });

        function bindevent_control()
        {
            // validate
            preventuser_typeenter($('#main-div'));


            var calltypecode = $("#CallTypeCode_IB").is(':checked') ? "IB" : "OB";

            // new appointment change
            $('#newappointment').click(function () {
                if ($(this).hasClass('btn-primary')) {
                    $(this).removeClass('btn-primary').addClass('btn-default');
                    $('#appointment-div').slideDown(150);
                }
                else {
                    $(this).removeClass('btn-default').addClass('btn-primary');
                    $('#appointment-div').slideUp(150);
                    $('#appointment-div :input').val('');
                }
                return false;
            });

            $('#ResponseCategoryCode').change(function () {
                _ajax_binddropdown_responsereason($(this).val());
            });
        }
    </script>
}
@if (ViewBag.NoAssignment != null && ViewBag.NoAssignment)
{
    <script>
        pop_message('ข้อความ', 'ไม่พบข้อมูลการมอบหมายลีด หรือข้อมูลไม่ถูกต้อง กรุณาเลือกข้อมูลจากลีดที่ได้รับมอบหมาย');
    </script>
}

GT.CRMApplication.WebMVC/Views/Prospect/DeleteActivity.cshtml
@using DM.Utilities.NetFramework.Databases.MsSQLs;
@using DM.Utilities.NetFramework.DataTables;
@using DM.Utilities.NetFramework.Models;
@using DM.Utilities.NetFramework.Generics;
@using GT.InboundApplication.Model.Common;
@model GT.InboundApplication.Model.CRM.Prospect_Activity
@{
    ViewBag.Title = "Delete Activity";
}

<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-md-12">
        <div class="col-md-10">
            <h2>ผู้ติดต่อ</h2>
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @if (User.IsAdmin())
                    {
                        @Html.ActionLink("รายการลีด", "Index", "LeadAssignment")
                    }
                    else
                    {
                        @Html.ActionLink("My Lead", "MyLead", "LeadAssignment")
                    }
                </li>
                <li>
                    @Html.ActionLink("ประวัติผู้ติดต่อ", "MainProfile", "Prospect", new { @id = Model.Prospect_Profile.ProspectId })
                </li>
                <li class="active">
                    <strong>ลบข้อมูลการติดต่อ</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.HttpMethodOverride(HttpVerbs.Delete)
    @Html.AntiForgeryToken()
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-4">
                @Html.Partial("_MainProfile", Model.Prospect_Profile)
            </div>
            <div class="col-sm-8">
                <div class="ibox">
                    <div class="ibox-title red-bg">
                        <h5>
                            <i class="fa fa-phone"></i>&nbsp;&nbsp;&nbsp;ลบข้อมูล การติดต่อ
                        </h5>
                    </div>
                    <div class="ibox-content animated fadeInDown">
                        <div class="form-horizontal">
                            @Html.HiddenFor(model => model.Prospect_Profile.ProspectId)
                            @Html.HiddenFor(model => model.ItemId)
                            @Html.HiddenFor(model => model.AppointmentId)
                            @Html.Partial("_ActivityView", Model)

                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-3">
                                    <button class="btn btn-primary" id="btn_submit" type="submit"><i class="fa fa-remove"></i>&nbsp;Confirm Delete</button>
                                    <a href="@Url.Action("MainProfile", "Prospect", new { @id = Model.Prospect_Profile.ProspectId })" class="btn btn-default">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

GT.CRMApplication.WebMVC/Views/Prospect/EditActivity.cshtml
@using DM.Utilities.NetFramework.Databases.MsSQLs;
@using DM.Utilities.NetFramework.DataTables;
@using DM.Utilities.NetFramework.Models;
@using DM.Utilities.NetFramework.Generics;
@using GT.InboundApplication.Model.Common;
@model GT.InboundApplication.Model.CRM.Prospect_Activity
@{
    ViewBag.Title = "Edit Activity";
}

<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-md-12">
        <div class="col-md-10">
            <h2>ผู้ติดต่อ</h2>
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @if (User.IsAdmin())
                    {
                        @Html.ActionLink("รายการลีด", "Index", "LeadAssignment")
                    }
                    else
                    {
                        @Html.ActionLink("My Lead", "MyLead", "LeadAssignment")
                    }
                </li>
                <li>
                    <a href="@Url.Action("MainProfile", "Prospect", new { @id = Model.Prospect_Profile.ProspectId })">ประวัติผู้ติดต่อ</a>
                </li>
                <li class="active">
                    <strong>แก้ไขข้อมูลการติดต่อ</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-sm-4">
                @Html.Partial("_MainProfile", Model.Prospect_Profile)
            </div>
            <div class="col-sm-8">
                <div class="ibox">
                    <div class="ibox-title red-bg">
                        <h5>
                            @{ var InventoryLead = "";
                                if (!Model.LeadAssignmentId.IsNullOrEmpty() && Model.LeadAssignmentId != 0) { InventoryLead = "[*ข้อมูลนี้ถูกส่งข้อมูลจากระบบบริหารและจัดการ Lead]"; }}
                            <i class="fa fa-phone"></i>&nbsp;&nbsp;&nbsp;แก้ไขข้อมูล การติดต่อ @InventoryLead @ViewBag.ExtendMessage
                        </h5>
                    </div>
                    @Html.Partial("_ActivityForm", Model)
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/onviews/Prospect/ActivityForm")
    @Scripts.Render("~/bundles/vuejs")
    @Scripts.Render("~/plugins/fullCalendar")

    <script type="text/javascript">
        $(document).ready(function () {
            bindevent_control();
            $('#appointment-div').hide();
            @ViewBag.RunScript
        });

        function bindevent_control() {
            // validate
            preventuser_typeenter($('#main-div'));
            // activity type change.

            // new appointment change
            $('#newappointment').click(function () {
                if ($(this).hasClass('btn-primary')) {
                    $(this).removeClass('btn-primary').addClass('btn-default');
                    $('#appointment-div').slideDown(150);
                }
                else {
                    $(this).removeClass('btn-default').addClass('btn-primary');
                    $('#appointment-div').slideUp(150);
                    $('#appointment-div :input').val('');
                }
                return false;
            });


            $('#ResponseCategoryCode').change(function () {
                _ajax_binddropdown_responsereason($(this).val());
            });
        }
    </script>
}

GT.CRMApplication.WebMVC/Views/Prospect/EditAppointment.cshtml
@model GT.InboundApplication.Model.CRM.Prospect_Appointment
<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-md-12">
        <div class="col-md-10">
            <h2>ผู้ติดต่อ</h2>
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    <a href="@Url.Action("MainProfile", "Prospect", new { @id = Model.Prospect_Activity.Prospect_Profile.ProspectId })">ประวัติผู้ติดต่อ</a>
                </li>
                <li class="active">
                    <strong>แก้ไขนัดหมาย</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-4">
            @Html.Partial("_MainProfile", Model.Prospect_Activity.Prospect_Profile)
        </div>
        <div class="col-lg-8">
            <div class="ibox float-e-margins">
                <div class="ibox-title gray-bg">
                    <h5>แก้ไขนัดหมาย</h5>
                </div>
                <div class="ibox-content">
                    @if (Request.Params["message"] != null)
                    {
                        <div class="alert alert-warning">@Request.Params["message"]</div>
                    }
                    @using (Html.BeginForm("EditAppointment","Prospect",FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.ItemId)
                            <div id="appointment-div" class="gray-bg border-all">
                                <div class="form-group" style="padding-top:10px;">
                                    <div class="col-sm-9 col-sm-offset-3">
                                        <font color="#C21B17"><h2><i class="fa fa-calendar"></i>&nbsp; การนัดหมาย</h2></font>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">วันที่นัดหมาย</label>
                                    <div class="col-sm-3">
                                        @Html.TextBoxFor(modelItem => modelItem.AppointmentDate, "{0:dd/MM/yyyy}", new { @class = "form-control input-date-future" })
                                    </div>
                                    <label class="col-sm-1 control-label">เวลา</label>
                                    <div class="col-sm-3">
                                        @Html.TextBoxFor(modelItem => modelItem.AppointmentTime, new { @class = "form-control input-time" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">หัวข้อ</label>
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(modelItem => modelItem.Topic, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">รายละเอียด</label>
                                    <div class="col-sm-8">
                                        @Html.TextAreaFor(modelItem => modelItem.Note, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-primary" />
                                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GT.CRMApplication.WebMVC/Views/Prospect/_PhoneNumber.cshtml
@using GT.InboundApplication.Model.Common
@model IEnumerable<GT.InboundApplication.Model.CRM.Prospect_PhoneNumber>
@foreach (var item in Model)
{
    <tr>
        <td>@item.PhoneNumberDisplay</td>
        <td>@item.Label</td>
        <td>@if(item.IsPrimary){<span class='badge badge-primary'>เบอร์หลัก</span>}</td>
        <td>
            <div class="btn-group">
                <button type="button" class="btn btn-xs btn-warning btn-edit-phonenumber" data-id="@item.ItemId" title="แก้ไข"><i class="fa fa-pencil"></i></button>
                <button type="button" class="btn btn-xs btn-primary btn-remove-phonenumber @(item.IsPrimary?"disabled":"")" data-id="@item.ItemId" data-phonenumber="@item.PhoneNumberDisplay" title="ลบ"><i class="fa fa-close"></i></button>
            </div>
        </td>
    </tr>
}