GT.CRMApplication.WebMVC/Controllers/CoveragesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using GT.InboundApplication.Model.CRM;

namespace GT.CRMApplication.WebMVC5.Controllers
{
    [Authorize]
    public class CoveragesController : Controller
    {
        private IGTCRMContext db = new IGTCRMContext();

        // GET: /Coverages/
        public ActionResult Index()
        {
            var dbset = db.CoverageSet;//.Include(l => l.Product);
            return View(dbset.ToList());
        }

        // GET: /Coverages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coverage Coverage = db.CoverageSet.Find(id);
            if (Coverage == null)
            {
                return HttpNotFound();
            }
            return View(Coverage);
        }

        // GET: /Coverages/Create
        public ActionResult Create()
        {
            var Coverage = new Coverage();
            return View(Coverage);
        }

        // POST: /Coverages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include= "CoverageTitle,CoverageContent, Active,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy,ProductId")] Coverage Coverage)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var item in errors)
            {
                string message = item.ErrorMessage;
                ModelState.AddModelError("", item.Exception);
            }
            if (ModelState.IsValid)
            {
				Coverage.CreatedBy =
				Coverage.UpdatedBy = User.Identity.GetUserId();
				Coverage.CreatedDate =
                Coverage.UpdatedDate = DateTime.Now;
                db.CoverageSet.Add(Coverage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Coverage);
        }

        // GET: /Coverages/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coverage Coverage = db.CoverageSet.Find(id);
            if (Coverage == null)
            {
                return HttpNotFound();
            }
            return View(Coverage);
        }

        // POST: /Coverages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CoverageTitle,CoverageContent, Active,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy")] Coverage Coverage)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var item in errors)
            {
                string message = item.ErrorMessage;
                ModelState.AddModelError("", item.Exception);
            }
            if (ModelState.IsValid)
            {
				Coverage.UpdatedBy = User.Identity.GetUserId();
			    Coverage.UpdatedDate = DateTime.Now;
                db.Entry(Coverage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Coverage);
        }

        // GET: /Coverages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coverage Coverage = db.CoverageSet.Find(id);
            if (Coverage == null)
            {
                return HttpNotFound();
            }
            return View(Coverage);
        }

        // POST: /Coverages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Coverage Coverage = db.CoverageSet.Find(id);
            db.CoverageSet.Remove(Coverage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GT.CRMApplication.WebMVC/Views/Coverages/Create.cshtml
@model GT.InboundApplication.Model.CRM.Coverage

@{
    ViewBag.Title = "Coverage";
}

@using (Html.BeginForm())
{
    <div class="row wrapper border-bottom gray-bg page-heading">
        <div class="col-sm-8">
            <h2>Coverage</h2>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("ความคุ้มครอง", "Index", "Coverages")
                </li>
                <li class="active">
                    <strong>สร้าง Coverage</strong>
                </li>
            </ol>
        </div>

        <div class="col-sm-4">
            <div class="title-action">
                <input type="submit" value="Save" onclick="savedata()" class="btn btn-primary" />
                @Html.ActionLink("ยกเลิก", "Index", "Coverages", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>

    <div class="row" style="padding-top:20px;">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create Coverage</h5>
                </div>
                <div class="ibox-content">
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.CoverageTitle, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CoverageTitle)
                                @Html.ValidationMessageFor(model => model.CoverageTitle)
                            </div>
                            <div style="display:none;">
                                @Html.HiddenFor(model => model.CoverageContent)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Active)
                                @Html.ValidationMessageFor(model => model.Active)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ibox-content no-padding">
        <div class="summernote">
            @Html.Raw(Model.CoverageContent)
        </div>
    </div>
}

@section Styles {
    @GTStyles.Render("~/plugins/summernoteStyles")
}

@section Scripts {
    @GTScripts.Render("~/plugins/summernote")

}
<script type="text/javascript">
    $(document).ready(function () {
        $('.summernote').summernote();
    });

    function savedata() {
        $('#CoverageContent').val($(".note-editable").html());
        return true;
    }
</script>

GT.CRMApplication.WebMVC/Views/Coverages/Delete.cshtml
@model GT.InboundApplication.Model.CRM.Coverage

@{
    ViewBag.Title = "Coverage";
	var title = ViewBag.Title;
	var mode = "ลบข้อมูล";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom gray-bg page-heading">
	<div class="col-sm-12">
		<div class="col-sm-4">
			<h2>@title</h2>
			<ol class="breadcrumb">
				<li>
					@Html.ActionLink("หน้าแรก","Index","Home")
				</li>
				<li>
				  @Html.ActionLink("รายการ", "Index")
				</li>
				<li class="active">
					<strong>@mode @title</strong>
				</li>
			</ol>
		</div>
		<div class="col-sm-8">
			<div class="title-action">
				@Html.ActionLink("ย้อนกลับ", "Index", null, new { @class = "btn btn-primary"})
			</div>
		</div>
	</div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title gray-bg">
                    <h5>@mode @title</h5>
                </div>
                <div class="ibox-content">
				<h4 class="text-danger">คุณต้องการลบข้อมูลนี้ใช่หรือไม่ ?</h4>
				 <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CoverageTitle)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("ย้อนกลับ", "Index", null, new { @class = "btn btn-white"})
        </div>
    }



                </div>
            </div>
        </div>
    </div>
 </div>

GT.CRMApplication.WebMVC/Views/Coverages/Edit.cshtml
@model GT.InboundApplication.Model.CRM.Coverage

@{
    ViewBag.Title = "Coverage";
}

@using (Html.BeginForm())
{
    <div class="row wrapper border-bottom gray-bg page-heading">
        <div class="col-sm-8">
            <h2>Coverage</h2>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("ตั้งค่า", "Preferences", "Application")
                </li>
                <li>
                    @Html.ActionLink("ความคุ้มครอง", "Index", "Coverages")
                </li>
                <li class="active">
                    <strong>แก้ไข Coverage</strong>
                </li>
            </ol>
        </div>

        <div class="col-sm-4">
            <div class="title-action">
                <input type="submit" value="Save" onclick="savedata()" class="btn btn-primary" />
                @Html.ActionLink("ยกเลิก", "Index", "Coverages", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>

    <div class="row" style="padding-top:20px;">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit Coverage</h5>
                </div>
                <div class="ibox-content">
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.CoverageTitle, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CoverageTitle)
                                @Html.ValidationMessageFor(model => model.CoverageTitle)
                            </div>
                            <div style="display:none;">
                                @Html.HiddenFor(model => model.CoverageContent)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Active)
                                @Html.ValidationMessageFor(model => model.Active)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ibox-content no-padding">
        <div class="summernote">
            @Html.Raw(Model.CoverageContent)
        </div>
    </div>
}

@section Styles {
    @GTStyles.Render("~/plugins/summernoteStyles")
}

@section Scripts {
    @GTScripts.Render("~/plugins/summernote")

}
<script type="text/javascript">
    $(document).ready(function () {
        $('.summernote').summernote();
    });

    function savedata() {
        $('#CoverageContent').val($(".note-editable").html());
        return true;
    }
</script>

GT.CRMApplication.WebMVC/Views/Coverages/Index.cshtml
@model IEnumerable<GT.InboundApplication.Model.CRM.Coverage>

@{
    ViewBag.Title = "Coverage";
    var title = ViewBag.Title;
    var mode = "รายการ";
}

<div class="row wrapper border-bottom gray-bg page-heading">
    <div class="col-sm-12">
        <div class="col-sm-4">
            <h2>@title</h2>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("หน้าแรก", "Index", "Home")
                </li>
                <li class="active">
                    <strong>@mode @title</strong>
                </li>
            </ol>
        </div>
        <div class="col-sm-8">
            <div class="title-action">
                <a href="@Url.Action("Create")" class="btn btn-primary btn-xs">สร้าง @title</a>
            </div>
        </div>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title gray-bg">
                    <h5>@mode @title</h5>
                    <div class="ibox-tools">
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover dataTables">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.CoverageTitle)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Active)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UpdatedDate)
                                </th>
                                <th>จัดการข้อมูล</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CoverageTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        @Html.ActionLink("แก้ไข", "Edit", new { id = item.Id }, new { @class = "btn btn-white btn-sm" })
                                        @Html.ActionLink("ลบ", "Delete", new { id = item.Id }, new { @class = "btn btn-white btn-sm" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>



@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/jeditable")
    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables').DataTable({
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });

        });
    </script>
}